//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoExchange
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class PoolsNew
    {
        public int id { get; set; }
        [DisplayName("Email")]
        public string email { get; set; }
        [DisplayName("Pool Name")]
        public string pool_name { get; set; }
        [DisplayName("Amount to Stake")]
        public double staked_amount { get; set; }
    }
}
