//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoExchange
{
    using System;
    using System.Collections.Generic;
    
    public partial class Portfolio
    {
        public int id { get; set; }
        public int userid { get; set; }
        public string coin_name { get; set; }
        public string wallet_address { get; set; }
        public double value { get; set; }
        public double staked_amount { get; set; }
        public double available_amount { get; set; }
    
        public virtual User User { get; set; }
    }
}
